### ISSUE TITLE
Visual feedback for sliding

### ISSUE THREAD

**Issue by Tmac4930** [luke-goldfain/Hangtime#26]
Create feedback systems for the character sliding action.

**Comment by luke-goldfain** [comment]
Sliding now causes the camera to move down. Smoke particles will be added next.

**Comment by luke-goldfain** [comment]
Keeping this in "In Progress" because I still plan on adding the particle effect.

**Comment by luke-goldfain** [comment]
I finally got around to adding the smoke particle effect to this. Sliding done!
