### ISSUE TITLE
Bug: MiniCam (Clone) spawns with rotation 0 on the X axis

### ISSUE THREAD

**Issue by Tmac4930** [luke-goldfain/Hangtime#68]
This bug is preventing the player from viewing minimap HUD elements. When the player spawns the Minimap camera located in the HUD clone spawns with incorrect rotations. Instead of rotation 90 on X-axis, the camera spawns on a rotation of 0 on the X-axis, making it impossible to see the minimap HUD.

**Comment by luke-goldfain** [comment]
When this happened, I was messing with the camera following player rotation and screwed up which axes the camera needed to copy. A fixed version that follows rotation is in the current master branch.

**Comment by Tmac4930** [comment]
Looking great! Minimap is fully functional!
